export interface ParamSchema {
  name: string;
  label: string;
  type: 'text' | 'number' | 'select' | 'boolean' | 'variable' | 'url' | 'textarea';
  placeholder?: string;
  options?: string[];
  required?: boolean;
  defaultValue?: string;
}

export interface ActionDefinition {
  type: string;
  label: string;
  icon: string;
  category: string;
  color: string;
  description: string;
  hint?: string;     // Usage guideline shown inside the ActionCard
  params: ParamSchema[];
  outputType?: string;
  isBlock?: boolean;
}

export const ACTION_CATEGORIES = [
  { id: 'scripting', label: 'Scripting', icon: '📱', color: '#6366f1' },
  { id: 'web', label: 'Web & Network', icon: '🌐', color: '#0ea5e9' },
  { id: 'files', label: 'Files & Storage', icon: '📁', color: '#f59e0b' },
  { id: 'media', label: 'Media', icon: '📸', color: '#ec4899' },
  { id: 'location', label: 'Location & Maps', icon: '🗺️', color: '#10b981' },
  { id: 'communication', label: 'Communication', icon: '📞', color: '#8b5cf6' },
  { id: 'audio', label: 'Audio & Speech', icon: '🔊', color: '#f97316' },
  { id: 'device', label: 'Device', icon: '🔧', color: '#64748b' },
  { id: 'math', label: 'Math & Logic', icon: '📊', color: '#14b8a6' },
];

export const ACTIONS_LIBRARY: ActionDefinition[] = [
  // ─── SCRIPTING ──────────────────────────────────────────────────
  {
    type: 'scripting.text',
    label: 'Text',
    icon: '📝',
    category: 'scripting',
    color: '#6366f1',
    description: 'Creates a text value',
    hint: 'Bir metin değeri üretir. Çıktısını bir sonraki action\'a aktarmak için "Set Variable" ile saklayabilirsiniz. Örneğin: "Merhaba {{name}}" gibi dinamik içerik yazabilirsiniz.',
    params: [
      { name: 'text', label: 'Text Content', type: 'textarea', placeholder: 'Enter text...', required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'scripting.number',
    label: 'Number',
    icon: '🔢',
    category: 'scripting',
    color: '#6366f1',
    description: 'Creates a number value',
    hint: 'Sayısal bir değer üretir. Math & Logic kategorisindeki hesaplama action\'larında girdi olarak kullanmak için "Set Variable" ile kaydedin.',
    params: [
      { name: 'number', label: 'Number', type: 'number', placeholder: '0', required: true },
    ],
    outputType: 'number',
  },
  {
    type: 'scripting.get_variable',
    label: 'Get Variable',
    icon: '📦',
    category: 'scripting',
    color: '#6366f1',
    description: 'Gets the value of a named variable',
    hint: 'Daha önce "Set Variable" ile kaydettiğiniz bir değişkeni okur. Değişken adı büyük/küçük harf duyarlıdır — kaydettiğinizle aynı yazın. Çıktıyı başka action\'larda girdi olarak kullanabilirsiniz.',
    params: [
      { name: 'variable', label: 'Variable Name', type: 'text', placeholder: 'myVariable', required: true },
    ],
    outputType: 'any',
  },
  {
    type: 'scripting.set_variable',
    label: 'Set Variable',
    icon: '🗂️',
    category: 'scripting',
    color: '#6366f1',
    description: 'Stores a value in a named variable',
    hint: 'Bir değeri isimlendirerek saklar. "Variable Name" alanı camelCase olmalıdır (örn. userLocation, apiResult). "Value" alanına doğrudan değer veya önceki bir action\'ın çıktısını girebilirsiniz.',
    params: [
      { name: 'variable', label: 'Variable Name', type: 'text', placeholder: 'myVariable', required: true },
      { name: 'value', label: 'Value', type: 'text', placeholder: 'value or variable reference', required: true },
    ],
  },
  {
    type: 'scripting.if',
    label: 'If',
    icon: '🔀',
    category: 'scripting',
    color: '#6366f1',
    description: 'Conditionally executes actions',
    hint: 'Koşullu dallanma sağlar. "Input" alanına karşılaştırmak istediğiniz değişken adını yazın, "Condition" ile karşılaştırma türünü seçin. "is empty" / "is not empty" seçeneklerinde "Value" alanı boş bırakılabilir.',
    isBlock: true,
    params: [
      { name: 'input', label: 'Input', type: 'text', placeholder: 'Variable or value', required: true },
      { name: 'condition', label: 'Condition', type: 'select', options: ['equals', 'does not equal', 'contains', 'does not contain', 'begins with', 'ends with', 'is greater than', 'is less than', 'is empty', 'is not empty'], required: true },
      { name: 'value', label: 'Value', type: 'text', placeholder: 'Compare against...', required: false },
    ],
  },
  {
    type: 'scripting.repeat',
    label: 'Repeat',
    icon: '🔁',
    category: 'scripting',
    color: '#6366f1',
    description: 'Repeats actions a set number of times',
    hint: 'Belirtilen sayı kadar döngü çalıştırır. Döngü içindeki action\'lar bu kart altına eklenir. Döngü sayacına "Repeat Index" adlı otomatik değişkenle erişebilirsiniz (0\'dan başlar).',
    isBlock: true,
    params: [
      { name: 'count', label: 'Repeat Count', type: 'number', placeholder: '3', required: true },
    ],
  },
  {
    type: 'scripting.wait',
    label: 'Wait',
    icon: '⏳',
    category: 'scripting',
    color: '#6366f1',
    description: 'Pauses execution for a duration',
    hint: 'Shortcut\'u belirtilen süre kadar duraklatır. Özellikle bir API çağrısından sonra sonucu beklemek veya animasyonlar arası gecikme eklemek için kullanışlıdır.',
    params: [
      { name: 'seconds', label: 'Seconds', type: 'number', placeholder: '1', required: true },
    ],
  },
  {
    type: 'scripting.show_alert',
    label: 'Show Alert',
    icon: '🔔',
    category: 'scripting',
    color: '#6366f1',
    description: 'Shows an alert dialog to the user',
    hint: 'Kullanıcıya bir popup mesaj gösterir. "Show Cancel Button" açıksa kullanıcı iptal edebilir — iptal edildiğinde shortcut durur. Önemli bildirimler veya onay adımları için kullanın.',
    params: [
      { name: 'title', label: 'Title', type: 'text', placeholder: 'Alert Title', required: true },
      { name: 'message', label: 'Message', type: 'textarea', placeholder: 'Alert message body', required: false },
      { name: 'show_cancel', label: 'Show Cancel Button', type: 'boolean', defaultValue: 'false' },
    ],
  },
  {
    type: 'scripting.show_notification',
    label: 'Show Notification',
    icon: '🔕',
    category: 'scripting',
    color: '#6366f1',
    description: 'Shows a system notification',
    hint: 'Ekranın üstünde görünen bildirim banner\'ı gösterir. Alert\'ten farklı olarak shortcut\'u durdurmaz, arka planda çalışmaya devam eder. Tamamlanma bildirimleri için idealdir.',
    params: [
      { name: 'title', label: 'Title', type: 'text', placeholder: 'Notification Title', required: true },
      { name: 'body', label: 'Body', type: 'textarea', placeholder: 'Notification body', required: false },
      { name: 'sound', label: 'Play Sound', type: 'boolean', defaultValue: 'true' },
    ],
  },
  {
    type: 'scripting.open_url',
    label: 'Open URL',
    icon: '🔗',
    category: 'scripting',
    color: '#6366f1',
    description: 'Opens a URL in the default browser or app',
    hint: 'Bir URL\'yi Safari veya ilgili uygulamada açar. Uygulama deep link\'leri de buraya girilebilir (örn. maps://, tel://, mailto:). URL\'yi değişkenden almak için değişken adını girin.',
    params: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'https://...', required: true },
    ],
  },
  {
    type: 'scripting.open_app',
    label: 'Open App',
    icon: '📲',
    category: 'scripting',
    color: '#6366f1',
    description: 'Opens a specific app on the device',
    hint: 'Cihazdaki yüklü bir uygulamayı açar. Uygulama adını tam olarak girin (örn. Safari, Maps, Settings, Mail). Özel uygulamalar için App Store\'daki görünen adı kullanın.',
    params: [
      { name: 'app', label: 'App Name', type: 'text', placeholder: 'Safari, Maps, Settings...', required: true },
    ],
  },
  {
    type: 'scripting.dictionary',
    label: 'Dictionary',
    icon: '📚',
    category: 'scripting',
    color: '#6366f1',
    description: 'Creates a key-value dictionary',
    hint: 'Anahtar-değer çiftlerinden oluşan bir sözlük oluşturur. API\'ye göndereceğiniz JSON gövdesini veya ayarları saklamak için kullanışlıdır. "Get Dictionary Value" ile tek bir değeri okuyabilirsiniz.',
    params: [
      { name: 'key', label: 'Key', type: 'text', placeholder: 'keyName', required: true },
      { name: 'value', label: 'Value', type: 'text', placeholder: 'value', required: true },
    ],
    outputType: 'dictionary',
  },
  {
    type: 'scripting.list',
    label: 'List',
    icon: '📋',
    category: 'scripting',
    color: '#6366f1',
    description: 'Creates a list of items',
    hint: 'Virgülle ayrılmış öğelerden bir liste oluşturur. "Repeat with Each" ile bu listenin her öğesi üzerinde döngü kurabilirsiniz. "Choose from List" ile kullanıcıya seçim yaptırabilirsiniz.',
    params: [
      { name: 'items', label: 'Items (comma separated)', type: 'textarea', placeholder: 'Item 1, Item 2, Item 3', required: true },
    ],
    outputType: 'list',
  },
  {
    type: 'scripting.choose_from_menu',
    label: 'Choose from Menu',
    icon: '📌',
    category: 'scripting',
    color: '#6366f1',
    description: 'Shows a menu for the user to pick from',
    hint: 'Kullanıcıya bir seçim menüsü gösterir. Seçilen değer shortcut\'ın çıktısı olur. Bunu "If" ile kombinleyerek seçime göre farklı dallar oluşturabilirsiniz.',
    params: [
      { name: 'prompt', label: 'Prompt', type: 'text', placeholder: 'Choose an option', required: true },
      { name: 'options', label: 'Options (comma separated)', type: 'textarea', placeholder: 'Option 1, Option 2, Option 3', required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'scripting.get_current_date',
    label: 'Get Current Date',
    icon: '📅',
    category: 'scripting',
    color: '#6366f1',
    description: 'Gets the current date and time',
    params: [],
    outputType: 'date',
  },
  {
    type: 'scripting.format_date',
    label: 'Format Date',
    icon: '🗓️',
    category: 'scripting',
    color: '#6366f1',
    description: 'Formats a date to a string',
    params: [
      { name: 'date', label: 'Date Variable', type: 'text', placeholder: 'dateVariable', required: true },
      { name: 'format', label: 'Format', type: 'select', options: ['Short', 'Medium', 'Long', 'Relative', 'ISO 8601'], required: true },
    ],
    outputType: 'text',
  },

  // ─── WEB & NETWORK ──────────────────────────────────────────────
  {
    type: 'web.get_url',
    label: 'Get Contents of URL',
    icon: '🌐',
    category: 'web',
    color: '#0ea5e9',
    description: 'Performs an HTTP request and returns the result',
    hint: 'Bir URL\'ye HTTP isteği gönderir ve yanıtı döndürür. Headers alanına JSON formatında yetkilendirme bilgisi ekleyin (örn. {"Authorization": "Bearer TOKEN"}). POST/PUT için Body alanına JSON gövdesi girin. Yanıt genellikle JSON metin olarak döner — "Get Dictionary from Input" ile parse edebilirsiniz.',
    params: [
      { name: 'url', label: 'URL', type: 'url', placeholder: 'https://api.example.com/data', required: true },
      { name: 'method', label: 'Method', type: 'select', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'], required: true, defaultValue: 'GET' },
      { name: 'headers', label: 'Headers (JSON)', type: 'textarea', placeholder: '{"Authorization": "Bearer ..."}', required: false },
      { name: 'body', label: 'Request Body (JSON)', type: 'textarea', placeholder: '{"key": "value"}', required: false },
    ],
    outputType: 'text',
  },
  {
    type: 'web.search',
    label: 'Search Web',
    icon: '🔍',
    category: 'web',
    color: '#0ea5e9',
    description: 'Opens a web search',
    hint: 'Seçilen arama motorunda arama yapıp tarayıcıyı açar. Değişken kullanabilirsiniz: Örneğin arama sorgusu olarak "searchQuery" değişkenini girebilirsiniz. YouTube araması için video içerik önerileri almaya yarar.',
    params: [
      { name: 'query', label: 'Search Query', type: 'text', placeholder: 'What to search for', required: true },
      { name: 'engine', label: 'Search Engine', type: 'select', options: ['Google', 'Bing', 'DuckDuckGo', 'YouTube'], required: true, defaultValue: 'Google' },
    ],
  },
  {
    type: 'web.get_ip',
    label: 'Get Current IP Address',
    icon: '🖥️',
    category: 'web',
    color: '#0ea5e9',
    description: 'Gets the current public IP address',
    params: [
      { name: 'type', label: 'IP Type', type: 'select', options: ['External', 'Internal'], defaultValue: 'External' },
    ],
    outputType: 'text',
  },
  {
    type: 'web.base64_encode',
    label: 'Base64 Encode',
    icon: '🔒',
    category: 'web',
    color: '#0ea5e9',
    description: 'Encodes text to Base64',
    params: [
      { name: 'input', label: 'Input Text', type: 'text', placeholder: 'Text to encode', required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'web.base64_decode',
    label: 'Base64 Decode',
    icon: '🔓',
    category: 'web',
    color: '#0ea5e9',
    description: 'Decodes a Base64 string',
    params: [
      { name: 'input', label: 'Base64 String', type: 'text', placeholder: 'Base64 encoded text', required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'web.url_encode',
    label: 'URL Encode',
    icon: '🔐',
    category: 'web',
    color: '#0ea5e9',
    description: 'URL-encodes a string',
    params: [
      { name: 'input', label: 'Text', type: 'text', placeholder: 'Text to encode', required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'web.hash',
    label: 'Hash Text',
    icon: '#️⃣',
    category: 'web',
    color: '#0ea5e9',
    description: 'Hashes text using a chosen algorithm',
    hint: 'Metni tek yönlü hash fonksiyonuyla şifreler. Güvenlik uygulamalarında SHA-256 önerilir. MD5 geriye dönük uyumluluk için kullanılabilir ancak kriptografik açıdan zayıftır. Çıktı hex string olarak döner.',
    params: [
      { name: 'input', label: 'Input Text', type: 'text', placeholder: 'Text to hash', required: true },
      { name: 'algorithm', label: 'Algorithm', type: 'select', options: ['MD5', 'SHA-1', 'SHA-256', 'SHA-512'], required: true, defaultValue: 'SHA-256' },
    ],
    outputType: 'text',
  },

  // ─── FILES & STORAGE ────────────────────────────────────────────
  {
    type: 'files.get_file',
    label: 'Get File',
    icon: '📂',
    category: 'files',
    color: '#f59e0b',
    description: 'Gets a file from the file system',
    hint: 'Cihazdaki dosya sisteminden bir dosya okur. iOS\'ta yollar genellikle iCloud Drive veya Dosyalar uygulamasına göre belirtilir (örn. /iCloud Drive/Shortcuts/data.txt). Çıktıyı "Save File" veya "Share" ile kullanabilirsiniz.',
    params: [
      { name: 'path', label: 'File Path', type: 'text', placeholder: '/path/to/file.txt', required: true },
    ],
    outputType: 'file',
  },
  {
    type: 'files.save_file',
    label: 'Save File',
    icon: '💾',
    category: 'files',
    color: '#f59e0b',
    description: 'Saves content to a file',
    params: [
      { name: 'content', label: 'Content', type: 'text', placeholder: 'Content to save', required: true },
      { name: 'path', label: 'Destination Path', type: 'text', placeholder: '/path/to/output.txt', required: true },
      { name: 'overwrite', label: 'Overwrite Existing', type: 'boolean', defaultValue: 'false' },
    ],
  },
  {
    type: 'files.delete_file',
    label: 'Delete File',
    icon: '🗑️',
    category: 'files',
    color: '#f59e0b',
    description: 'Deletes a file',
    params: [
      { name: 'path', label: 'File Path', type: 'text', placeholder: '/path/to/file.txt', required: true },
    ],
  },
  {
    type: 'files.get_file_details',
    label: 'Get File Details',
    icon: 'ℹ️',
    category: 'files',
    color: '#f59e0b',
    description: 'Gets details about a file',
    params: [
      { name: 'path', label: 'File Path', type: 'text', placeholder: '/path/to/file', required: true },
      { name: 'detail', label: 'Detail', type: 'select', options: ['Name', 'File Extension', 'Size', 'Creation Date', 'Last Modified Date', 'File Path'], required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'files.append_to_file',
    label: 'Append to File',
    icon: '📎',
    category: 'files',
    color: '#f59e0b',
    description: 'Appends text to the end of a file',
    params: [
      { name: 'content', label: 'Content', type: 'textarea', placeholder: 'Text to append', required: true },
      { name: 'path', label: 'File Path', type: 'text', placeholder: '/path/to/file.txt', required: true },
      { name: 'make_new_line', label: 'Add New Line Before', type: 'boolean', defaultValue: 'true' },
    ],
  },
  {
    type: 'files.compress',
    label: 'Compress Archive',
    icon: '🗜️',
    category: 'files',
    color: '#f59e0b',
    description: 'Compresses files into an archive',
    params: [
      { name: 'input', label: 'Input Path', type: 'text', placeholder: '/path/to/folder', required: true },
      { name: 'format', label: 'Format', type: 'select', options: ['ZIP', 'TAR', 'GZIP'], required: true, defaultValue: 'ZIP' },
    ],
    outputType: 'file',
  },
  {
    type: 'files.create_folder',
    label: 'Create Folder',
    icon: '📁',
    category: 'files',
    color: '#f59e0b',
    description: 'Creates a new folder',
    params: [
      { name: 'path', label: 'Folder Path', type: 'text', placeholder: '/path/to/new-folder', required: true },
    ],
  },

  // ─── MEDIA ──────────────────────────────────────────────────────
  {
    type: 'media.take_photo',
    label: 'Take Photo',
    icon: '📷',
    category: 'media',
    color: '#ec4899',
    description: 'Takes a photo with the camera',
    hint: 'Kamerayla fotoğraf çeker. "Show Preview" kapalıysa önizleme olmadan anında çekilir. Çıktı olarak Image nesnesi döner — bunu "Resize Image" veya "Save File" ile kullanabilirsiniz. Birden fazla fotoğraf için "Count" parametresini artırın.',
    params: [
      { name: 'camera', label: 'Camera', type: 'select', options: ['Back', 'Front'], defaultValue: 'Back' },
      { name: 'show_preview', label: 'Show Preview', type: 'boolean', defaultValue: 'true' },
    ],
    outputType: 'image',
  },
  {
    type: 'media.take_video',
    label: 'Take Video',
    icon: '🎥',
    category: 'media',
    color: '#ec4899',
    description: 'Records a video with the camera',
    params: [
      { name: 'camera', label: 'Camera', type: 'select', options: ['Back', 'Front'], defaultValue: 'Back' },
      { name: 'quality', label: 'Quality', type: 'select', options: ['Low', 'Medium', 'High', 'Highest'], defaultValue: 'High' },
    ],
    outputType: 'video',
  },
  {
    type: 'media.get_latest_photo',
    label: 'Get Latest Photo',
    icon: '🖼️',
    category: 'media',
    color: '#ec4899',
    description: 'Gets the most recent photo from the photo library',
    params: [
      { name: 'count', label: 'Number of Photos', type: 'number', placeholder: '1', required: true },
    ],
    outputType: 'image',
  },
  {
    type: 'media.resize_image',
    label: 'Resize Image',
    icon: '↔️',
    category: 'media',
    color: '#ec4899',
    description: 'Resizes an image to specified dimensions',
    params: [
      { name: 'image', label: 'Image Variable', type: 'text', placeholder: 'imageVariable', required: true },
      { name: 'width', label: 'Width (px)', type: 'number', placeholder: '1080', required: true },
      { name: 'height', label: 'Height (px)', type: 'number', placeholder: '1920', required: false },
    ],
    outputType: 'image',
  },
  {
    type: 'media.crop_image',
    label: 'Crop Image',
    icon: '✂️',
    category: 'media',
    color: '#ec4899',
    description: 'Crops an image to a specific area',
    params: [
      { name: 'image', label: 'Image Variable', type: 'text', placeholder: 'imageVariable', required: true },
      { name: 'position', label: 'Position', type: 'select', options: ['Top Left', 'Top Right', 'Center', 'Bottom Left', 'Bottom Right', 'Custom'], required: true },
      { name: 'width', label: 'Width (px)', type: 'number', placeholder: '500', required: true },
      { name: 'height', label: 'Height (px)', type: 'number', placeholder: '500', required: true },
    ],
    outputType: 'image',
  },
  {
    type: 'media.convert_image',
    label: 'Convert Image',
    icon: '🔄',
    category: 'media',
    color: '#ec4899',
    description: 'Converts an image to a different format',
    params: [
      { name: 'image', label: 'Image Variable', type: 'text', placeholder: 'imageVariable', required: true },
      { name: 'format', label: 'Output Format', type: 'select', options: ['JPEG', 'PNG', 'HEIF', 'TIFF', 'BMP', 'PDF'], required: true, defaultValue: 'JPEG' },
    ],
    outputType: 'image',
  },
  {
    type: 'media.get_image_from_url',
    label: 'Get Image from URL',
    icon: '🔗',
    category: 'media',
    color: '#ec4899',
    description: 'Downloads an image from a URL',
    params: [
      { name: 'url', label: 'Image URL', type: 'url', placeholder: 'https://example.com/image.jpg', required: true },
    ],
    outputType: 'image',
  },
  {
    type: 'media.create_pdf',
    label: 'Create PDF',
    icon: '📄',
    category: 'media',
    color: '#ec4899',
    description: 'Creates a PDF from content',
    params: [
      { name: 'content', label: 'Content or URL', type: 'text', placeholder: 'Variable or URL', required: true },
    ],
    outputType: 'file',
  },

  // ─── LOCATION & MAPS ────────────────────────────────────────────
  {
    type: 'location.get_current',
    label: 'Get Current Location',
    icon: '📍',
    category: 'location',
    color: '#10b981',
    description: 'Gets the device\'s current GPS location',
    hint: 'GPS üzerinden cihazın anlık konumunu alır. Konum servislerinin açık olması ve uygulamanın izin almış olması gerekir. Çıktı bir Location nesnesidir — "Get Address" veya "Show in Maps" ile zincirleyebilirsiniz.',
    params: [],
    outputType: 'location',
  },
  {
    type: 'location.get_address',
    label: 'Get Address',
    icon: '🏠',
    category: 'location',
    color: '#10b981',
    description: 'Converts a location to a street address',
    params: [
      { name: 'location', label: 'Location Variable', type: 'text', placeholder: 'locationVariable', required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'location.show_in_maps',
    label: 'Show in Maps',
    icon: '🗺️',
    category: 'location',
    color: '#10b981',
    description: 'Opens a location in Apple Maps',
    params: [
      { name: 'location', label: 'Location or Address', type: 'text', placeholder: 'Location variable or address text', required: true },
    ],
  },
  {
    type: 'location.get_distance',
    label: 'Get Distance',
    icon: '📏',
    category: 'location',
    color: '#10b981',
    description: 'Calculates distance between two locations',
    params: [
      { name: 'from', label: 'From Location', type: 'text', placeholder: 'Location variable or address', required: true },
      { name: 'to', label: 'To Location', type: 'text', placeholder: 'Location variable or address', required: true },
      { name: 'unit', label: 'Unit', type: 'select', options: ['km', 'miles', 'meters'], defaultValue: 'km' },
    ],
    outputType: 'number',
  },
  {
    type: 'location.get_weather',
    label: 'Get Weather Conditions',
    icon: '⛅',
    category: 'location',
    color: '#10b981',
    description: 'Gets current weather at a location',
    params: [
      { name: 'location', label: 'Location Variable', type: 'text', placeholder: 'locationVariable or leave empty for current', required: false },
      { name: 'detail', label: 'Detail', type: 'select', options: ['Conditions', 'Temperature', 'High', 'Low', 'Precipitation', 'Wind Speed', 'UV Index', 'Humidity', 'Feels Like'] },
    ],
    outputType: 'text',
  },
  {
    type: 'location.get_maps_url',
    label: 'Get Maps URL',
    icon: '🔗',
    category: 'location',
    color: '#10b981',
    description: 'Creates a Maps deep link URL for a location',
    params: [
      { name: 'location', label: 'Location or Address', type: 'text', placeholder: 'Address or coordinates', required: true },
    ],
    outputType: 'url',
  },

  // ─── COMMUNICATION ──────────────────────────────────────────────
  {
    type: 'comm.send_message',
    label: 'Send Message',
    icon: '💬',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Sends an iMessage or SMS',
    hint: 'iMessage veya SMS gönderir. Alıcı alanına telefon numarası veya Apple ID e-postası girin. Birden fazla alıcı için virgülle ayırın. Bu action iOS\'ta Mesajlar uygulamasını açar — gönder butonuna basmak kullanıcıya kalır.',
    params: [
      { name: 'to', label: 'Recipient (phone or email)', type: 'text', placeholder: '+1 555 000 0000', required: true },
      { name: 'message', label: 'Message', type: 'textarea', placeholder: 'Type your message', required: true },
    ],
  },
  {
    type: 'comm.send_email',
    label: 'Send Email',
    icon: '📧',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Composes and sends an email',
    params: [
      { name: 'to', label: 'To', type: 'text', placeholder: 'email@example.com', required: true },
      { name: 'subject', label: 'Subject', type: 'text', placeholder: 'Email subject', required: true },
      { name: 'body', label: 'Body', type: 'textarea', placeholder: 'Email body', required: true },
      { name: 'cc', label: 'CC', type: 'text', placeholder: 'cc@example.com', required: false },
    ],
  },
  {
    type: 'comm.call',
    label: 'Call Number',
    icon: '📞',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Calls a phone number',
    params: [
      { name: 'number', label: 'Phone Number', type: 'text', placeholder: '+1 555 000 0000', required: true },
    ],
  },
  {
    type: 'comm.facetime',
    label: 'FaceTime',
    icon: '📹',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Starts a FaceTime call',
    params: [
      { name: 'contact', label: 'Contact (phone or email)', type: 'text', placeholder: '+1 555 000 0000', required: true },
      { name: 'type', label: 'Call Type', type: 'select', options: ['Video', 'Audio'], defaultValue: 'Video' },
    ],
  },
  {
    type: 'comm.create_contact',
    label: 'Create Contact',
    icon: '👤',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Creates a new contact',
    params: [
      { name: 'first_name', label: 'First Name', type: 'text', placeholder: 'John', required: true },
      { name: 'last_name', label: 'Last Name', type: 'text', placeholder: 'Doe', required: false },
      { name: 'phone', label: 'Phone Number', type: 'text', placeholder: '+1 555 000 0000', required: false },
      { name: 'email', label: 'Email', type: 'text', placeholder: 'email@example.com', required: false },
    ],
  },
  {
    type: 'comm.find_contact',
    label: 'Find Contact',
    icon: '🔍',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Searches for a contact by name',
    params: [
      { name: 'name', label: 'Search Name', type: 'text', placeholder: 'Contact name', required: true },
    ],
    outputType: 'contact',
  },
  {
    type: 'comm.create_event',
    label: 'Create Calendar Event',
    icon: '📅',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Creates a calendar event',
    params: [
      { name: 'title', label: 'Title', type: 'text', placeholder: 'Meeting with Team', required: true },
      { name: 'start_date', label: 'Start Date', type: 'text', placeholder: 'Today at 3:00 PM', required: true },
      { name: 'end_date', label: 'End Date', type: 'text', placeholder: 'Today at 4:00 PM', required: true },
      { name: 'location', label: 'Location', type: 'text', placeholder: 'Conference Room A', required: false },
      { name: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Additional notes', required: false },
    ],
  },
  {
    type: 'comm.add_reminder',
    label: 'Add Reminder',
    icon: '⏰',
    category: 'communication',
    color: '#8b5cf6',
    description: 'Creates a reminder',
    params: [
      { name: 'title', label: 'Reminder Title', type: 'text', placeholder: 'Buy groceries', required: true },
      { name: 'due_date', label: 'Due Date', type: 'text', placeholder: 'Tomorrow at 10:00 AM', required: false },
      { name: 'list', label: 'List', type: 'text', placeholder: 'Reminders (or list name)', required: false },
    ],
  },

  // ─── AUDIO & SPEECH ─────────────────────────────────────────────
  {
    type: 'audio.speak_text',
    label: 'Speak Text',
    icon: '🔊',
    category: 'audio',
    color: '#f97316',
    description: 'Reads text aloud using text-to-speech',
    hint: 'Metni sesli okur (text-to-speech). "Wait Until Done" açıksa okuma bitene kadar shortcut devam etmez. Değişkenden metin okutabilirsiniz: Text alanına değişken adını yazın. Sessize alınmış cihazlarda çalışmayabilir.',
    params: [
      { name: 'text', label: 'Text to Speak', type: 'textarea', placeholder: 'Hello, world!', required: true },
      { name: 'voice', label: 'Voice', type: 'select', options: ['Default', 'Siri', 'Alex', 'Samantha'], defaultValue: 'Default' },
      { name: 'rate', label: 'Speaking Rate', type: 'select', options: ['Slow', 'Normal', 'Fast'], defaultValue: 'Normal' },
      { name: 'wait_until_done', label: 'Wait Until Done', type: 'boolean', defaultValue: 'true' },
    ],
  },
  {
    type: 'audio.play_sound',
    label: 'Play Sound',
    icon: '🎵',
    category: 'audio',
    color: '#f97316',
    description: 'Plays an audio file',
    params: [
      { name: 'file', label: 'Audio File Variable', type: 'text', placeholder: 'audioFileVariable', required: true },
    ],
  },
  {
    type: 'audio.set_volume',
    label: 'Set Volume',
    icon: '🔉',
    category: 'audio',
    color: '#f97316',
    description: 'Sets the device volume',
    params: [
      { name: 'volume', label: 'Volume (0-100)', type: 'number', placeholder: '50', required: true },
    ],
  },
  {
    type: 'audio.record_audio',
    label: 'Record Audio',
    icon: '🎙️',
    category: 'audio',
    color: '#f97316',
    description: 'Records audio from the microphone',
    params: [
      { name: 'quality', label: 'Quality', type: 'select', options: ['Normal', 'High', 'Very High'], defaultValue: 'Normal' },
      { name: 'start_immediately', label: 'Start Immediately', type: 'boolean', defaultValue: 'false' },
    ],
    outputType: 'audio',
  },

  // ─── DEVICE ─────────────────────────────────────────────────────
  {
    type: 'device.set_brightness',
    label: 'Set Brightness',
    icon: '☀️',
    category: 'device',
    color: '#64748b',
    description: 'Sets the screen brightness',
    hint: 'Ekran parlaklığını 0-100 arası bir değere ayarlar. Gece rutinleri için 10-20, okuma için 60-80 önerilir. "Get Device Details" ile mevcut parlaklık seviyesini okuyup önce saklayabilirsiniz.',
    params: [
      { name: 'brightness', label: 'Brightness (0-100)', type: 'number', placeholder: '80', required: true },
    ],
  },
  {
    type: 'device.set_wifi',
    label: 'Set Wi-Fi',
    icon: '📶',
    category: 'device',
    color: '#64748b',
    description: 'Turns Wi-Fi on or off',
    params: [
      { name: 'enabled', label: 'Wi-Fi Enabled', type: 'boolean', defaultValue: 'true' },
    ],
  },
  {
    type: 'device.set_bluetooth',
    label: 'Set Bluetooth',
    icon: '🔵',
    category: 'device',
    color: '#64748b',
    description: 'Turns Bluetooth on or off',
    params: [
      { name: 'enabled', label: 'Bluetooth Enabled', type: 'boolean', defaultValue: 'true' },
    ],
  },
  {
    type: 'device.set_do_not_disturb',
    label: 'Set Do Not Disturb',
    icon: '🌙',
    category: 'device',
    color: '#64748b',
    description: 'Toggles Do Not Disturb mode',
    params: [
      { name: 'enabled', label: 'Do Not Disturb Enabled', type: 'boolean', defaultValue: 'true' },
    ],
  },
  {
    type: 'device.set_airplane_mode',
    label: 'Set Airplane Mode',
    icon: '✈️',
    category: 'device',
    color: '#64748b',
    description: 'Toggles Airplane Mode',
    params: [
      { name: 'enabled', label: 'Airplane Mode Enabled', type: 'boolean', defaultValue: 'true' },
    ],
  },
  {
    type: 'device.get_battery',
    label: 'Get Battery Level',
    icon: '🔋',
    category: 'device',
    color: '#64748b',
    description: 'Gets the current battery percentage',
    params: [],
    outputType: 'number',
  },
  {
    type: 'device.get_details',
    label: 'Get Device Details',
    icon: '📱',
    category: 'device',
    color: '#64748b',
    description: 'Gets information about the device',
    params: [
      { name: 'detail', label: 'Detail', type: 'select', options: ['Device Name', 'Device Model', 'System Version', 'Screen Width', 'Screen Height', 'Current Language', 'Current Region', 'Device UDID'], required: true },
    ],
    outputType: 'text',
  },
  {
    type: 'device.set_wallpaper',
    label: 'Set Wallpaper',
    icon: '🖼️',
    category: 'device',
    color: '#64748b',
    description: 'Sets the device wallpaper',
    params: [
      { name: 'image', label: 'Image Variable', type: 'text', placeholder: 'imageVariable', required: true },
      { name: 'screen', label: 'Screen', type: 'select', options: ['Home Screen', 'Lock Screen', 'Both'], defaultValue: 'Both' },
    ],
  },
  {
    type: 'device.lock_screen',
    label: 'Lock Screen',
    icon: '🔒',
    category: 'device',
    color: '#64748b',
    description: 'Locks the device screen',
    params: [],
  },

  // ─── MATH & LOGIC ───────────────────────────────────────────────
  {
    type: 'math.calculate',
    label: 'Calculate Expression',
    icon: '🧮',
    category: 'math',
    color: '#14b8a6',
    description: 'Evaluates a mathematical expression',
    hint: 'Matematiksel ifadeyi hesaplar. Değişken adlarını doğrudan kullanabilirsiniz (örn. price * 1.18). Desteklenen operatörler: +, -, *, /, %, ^ (üs). Parantez kullanımı desteklenir. Sonuç sayısal değer olarak döner.',
    params: [
      { name: 'expression', label: 'Expression', type: 'text', placeholder: '(price * 1.18) / quantity', required: true },
    ],
    outputType: 'number',
  },
  {
    type: 'math.round',
    label: 'Round Number',
    icon: '🔵',
    category: 'math',
    color: '#14b8a6',
    description: 'Rounds a number to a given precision',
    params: [
      { name: 'number', label: 'Number', type: 'text', placeholder: 'numberVariable or 3.14', required: true },
      { name: 'mode', label: 'Round Mode', type: 'select', options: ['Normal', 'Always Round Up', 'Always Round Down', 'Round Toward Zero'], defaultValue: 'Normal' },
      { name: 'decimal_places', label: 'Decimal Places', type: 'number', placeholder: '2', required: true },
    ],
    outputType: 'number',
  },
  {
    type: 'math.random',
    label: 'Generate Random Number',
    icon: '🎲',
    category: 'math',
    color: '#14b8a6',
    description: 'Generates a random number in a range',
    params: [
      { name: 'min', label: 'Minimum', type: 'number', placeholder: '1', required: true },
      { name: 'max', label: 'Maximum', type: 'number', placeholder: '100', required: true },
    ],
    outputType: 'number',
  },
  {
    type: 'math.statistics',
    label: 'Statistics',
    icon: '📈',
    category: 'math',
    color: '#14b8a6',
    description: 'Performs statistical operations on a list',
    params: [
      { name: 'list', label: 'Number List Variable', type: 'text', placeholder: 'listVariable', required: true },
      { name: 'operation', label: 'Operation', type: 'select', options: ['Minimum', 'Maximum', 'Average', 'Sum', 'Count', 'Median', 'Mode', 'Range', 'Standard Deviation'], required: true },
    ],
    outputType: 'number',
  },
  {
    type: 'math.convert_units',
    label: 'Convert Units',
    icon: '📐',
    category: 'math',
    color: '#14b8a6',
    description: 'Converts a measurement between units',
    params: [
      { name: 'value', label: 'Value', type: 'text', placeholder: 'numberVariable or 100', required: true },
      { name: 'from_unit', label: 'From Unit', type: 'text', placeholder: 'km, kg, Celsius...', required: true },
      { name: 'to_unit', label: 'To Unit', type: 'text', placeholder: 'miles, lbs, Fahrenheit...', required: true },
    ],
    outputType: 'number',
  },
  {
    type: 'math.format_number',
    label: 'Format Number',
    icon: '🔢',
    category: 'math',
    color: '#14b8a6',
    description: 'Formats a number to a styled string',
    params: [
      { name: 'number', label: 'Number', type: 'text', placeholder: 'numberVariable or 1234.5', required: true },
      { name: 'format', label: 'Format', type: 'select', options: ['Decimal', 'Currency', 'Scientific', 'Percentage', 'Spell Out'], required: true },
    ],
    outputType: 'text',
  },
];
